// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (check_id, file_name) 
VALUES ($1, $2) 
ON CONFLICT (check_id) DO NOTHING
RETURNING id, check_id, shop_id, user_id, file_name, created_at
`

type CreateCheckParams struct {
	CheckID  string
	FileName string
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck, arg.CheckID, arg.FileName)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.CheckID,
		&i.ShopID,
		&i.UserID,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCheck = `-- name: DeleteCheck :exec
DELETE FROM checks WHERE id = $1
`

func (q *Queries) DeleteCheck(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCheck, id)
	return err
}

const getCheckByCheckID = `-- name: GetCheckByCheckID :one
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM checks WHERE check_id = $1
`

func (q *Queries) GetCheckByCheckID(ctx context.Context, checkID string) (Check, error) {
	row := q.db.QueryRow(ctx, getCheckByCheckID, checkID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.CheckID,
		&i.ShopID,
		&i.UserID,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckByID = `-- name: GetCheckByID :one
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM checks WHERE id = $1
`

func (q *Queries) GetCheckByID(ctx context.Context, id int32) (Check, error) {
	row := q.db.QueryRow(ctx, getCheckByID, id)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.CheckID,
		&i.ShopID,
		&i.UserID,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const getChecksByDateRange = `-- name: GetChecksByDateRange :many
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM checks 
WHERE ($1::timestamp IS NULL OR created_at >= $1)
AND ($2::timestamp IS NULL OR created_at <= $2)
ORDER BY created_at DESC
`

type GetChecksByDateRangeParams struct {
	Column1 pgtype.Timestamp
	Column2 pgtype.Timestamp
}

func (q *Queries) GetChecksByDateRange(ctx context.Context, arg GetChecksByDateRangeParams) ([]Check, error) {
	rows, err := q.db.Query(ctx, getChecksByDateRange, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.ShopID,
			&i.UserID,
			&i.FileName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateCheck = `-- name: GetOrCreateCheck :one
WITH inserted AS (
    INSERT INTO checks (check_id, shop_id, user_id, file_name, created_at) 
    VALUES ($1, $2, $3, $4, $5) 
    ON CONFLICT (check_id) DO NOTHING 
    RETURNING id, check_id, shop_id, user_id, file_name, created_at
)
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM inserted
UNION ALL
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM checks WHERE check_id = $1
LIMIT 1
`

type GetOrCreateCheckParams struct {
	CheckID   string
	ShopID    int32
	UserID    int32
	FileName  string
	CreatedAt pgtype.Timestamp
}

type GetOrCreateCheckRow struct {
	ID        int32
	CheckID   string
	ShopID    int32
	UserID    int32
	FileName  string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetOrCreateCheck(ctx context.Context, arg GetOrCreateCheckParams) (GetOrCreateCheckRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateCheck,
		arg.CheckID,
		arg.ShopID,
		arg.UserID,
		arg.FileName,
		arg.CreatedAt,
	)
	var i GetOrCreateCheckRow
	err := row.Scan(
		&i.ID,
		&i.CheckID,
		&i.ShopID,
		&i.UserID,
		&i.FileName,
		&i.CreatedAt,
	)
	return i, err
}

const listChecks = `-- name: ListChecks :many
SELECT id, check_id, shop_id, user_id, file_name, created_at FROM checks ORDER BY created_at DESC
`

func (q *Queries) ListChecks(ctx context.Context) ([]Check, error) {
	rows, err := q.db.Query(ctx, listChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.ShopID,
			&i.UserID,
			&i.FileName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
