// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32
	Name string
}

type Check struct {
	ID        int32
	CheckID   string
	FileName  string
	CreatedAt pgtype.Timestamp
}

type Product struct {
	ID             int32
	ProductID      int32
	CheckID        int32
	CategoryID     int32
	PricePerUnit   float64
	AmountOrWeight float64
}

type ProductName struct {
	ID   int32
	Name string
}

type ProductRelation struct {
	ID                 int32
	ProductID          int32
	IdenticalProductID int32
}
