// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32
	Name string
}

type Check struct {
	ID        int32
	CheckID   string
	ShopID    int32
	UserID    int32
	FileName  string
	CreatedAt pgtype.Timestamp
}

type Product struct {
	ID             int32
	ProductID      int32
	CheckID        int32
	CategoryID     int32
	PricePerUnit   float64
	AmountOrWeight float64
}

type ProductName struct {
	ID   int32
	Name string
}

type ProductRelation struct {
	ID                 int32
	ProductID          int32
	IdenticalProductID int32
}

type Shop struct {
	ID      int32
	BrandID int32
	Address string
	Lat     pgtype.Float8
	Lng     pgtype.Float8
}

type ShopBrand struct {
	ID   int32
	Name string
}

type Template struct {
	ID        int32
	Name      string
	UserID    pgtype.Int4
	IsDefault pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type TemplateProduct struct {
	ID             int32
	TemplateID     int32
	ProductNameID  int32
	AmountOrWeight float64
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Name         pgtype.Text
	CreatedAt    pgtype.Timestamp
}
