// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_relations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductRelation = `-- name: CreateProductRelation :one
INSERT INTO product_relations (product_name_id, identical_product_name_id) 
VALUES ($1, $2)
ON CONFLICT (product_name_id, identical_product_name_id) DO NOTHING 
RETURNING id, product_name_id, identical_product_name_id
`

type CreateProductRelationParams struct {
	ProductNameID          int32
	IdenticalProductNameID int32
}

func (q *Queries) CreateProductRelation(ctx context.Context, arg CreateProductRelationParams) (ProductRelation, error) {
	row := q.db.QueryRow(ctx, createProductRelation, arg.ProductNameID, arg.IdenticalProductNameID)
	var i ProductRelation
	err := row.Scan(&i.ID, &i.ProductNameID, &i.IdenticalProductNameID)
	return i, err
}

const deleteProductRelation = `-- name: DeleteProductRelation :exec
DELETE FROM product_relations 
WHERE product_name_id = $1 AND identical_product_name_id = $2
`

type DeleteProductRelationParams struct {
	ProductNameID          int32
	IdenticalProductNameID int32
}

func (q *Queries) DeleteProductRelation(ctx context.Context, arg DeleteProductRelationParams) error {
	_, err := q.db.Exec(ctx, deleteProductRelation, arg.ProductNameID, arg.IdenticalProductNameID)
	return err
}

const getIdenticalProductsWithDetailsByProductNameId = `-- name: GetIdenticalProductsWithDetailsByProductNameId :many
SELECT 
    pr.product_name_id,
    pr.identical_product_name_id,
    pn1.name as product_name,
    pn2.name as identical_product_name,
    p.price_per_unit,
    p.amount_or_weight,
    c.check_id
FROM product_relations pr
JOIN product_names pn1 ON pr.product_name_id = pn1.id
JOIN product_names pn2 ON pr.identical_product_name_id = pn2.id
LEFT JOIN products p ON pn1.id = p.product_id
LEFT JOIN checks c ON p.check_id = c.id
WHERE pr.product_name_id = $1
`

type GetIdenticalProductsWithDetailsByProductNameIdRow struct {
	ProductNameID          int32
	IdenticalProductNameID int32
	ProductName            string
	IdenticalProductName   string
	PricePerUnit           pgtype.Float8
	AmountOrWeight         pgtype.Float8
	CheckID                pgtype.Text
}

func (q *Queries) GetIdenticalProductsWithDetailsByProductNameId(ctx context.Context, productNameID int32) ([]GetIdenticalProductsWithDetailsByProductNameIdRow, error) {
	rows, err := q.db.Query(ctx, getIdenticalProductsWithDetailsByProductNameId, productNameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIdenticalProductsWithDetailsByProductNameIdRow
	for rows.Next() {
		var i GetIdenticalProductsWithDetailsByProductNameIdRow
		if err := rows.Scan(
			&i.ProductNameID,
			&i.IdenticalProductNameID,
			&i.ProductName,
			&i.IdenticalProductName,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.CheckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductRelationsByProductNameID = `-- name: GetProductRelationsByProductNameID :many
SELECT id, product_name_id, identical_product_name_id FROM product_relations WHERE product_name_id = $1
`

func (q *Queries) GetProductRelationsByProductNameID(ctx context.Context, productNameID int32) ([]ProductRelation, error) {
	rows, err := q.db.Query(ctx, getProductRelationsByProductNameID, productNameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductRelation
	for rows.Next() {
		var i ProductRelation
		if err := rows.Scan(&i.ID, &i.ProductNameID, &i.IdenticalProductNameID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithDetails = `-- name: ListProductsWithDetails :many
WITH canonical AS (
    SELECT 
        COALESCE(pr.product_name_id, pn.id) as canonical_id,
        pn.id as name_id
    FROM product_names pn
    LEFT JOIN product_relations pr ON pn.id = pr.identical_product_name_id
),
counts AS (
    SELECT canonical_id, COUNT(*) as total_purchases
    FROM canonical c
    JOIN products p ON c.name_id = p.product_id
    GROUP BY canonical_id
)
SELECT 
    p.id,
    pn.id as product_name_id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    c.check_id as check_id,
    cat.name as category_name,
    COALESCE(cnt.total_purchases, 0) as total_purchases
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
JOIN categories cat ON p.category_id = cat.id
LEFT JOIN counts cnt ON pn.id = cnt.canonical_id
WHERE pn.id NOT IN (
    SELECT identical_product_name_id FROM product_relations
)
ORDER BY p.id
`

type ListProductsWithDetailsRow struct {
	ID             int32
	ProductNameID  int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CheckID        string
	CategoryName   string
	TotalPurchases int64
}

func (q *Queries) ListProductsWithDetails(ctx context.Context) ([]ListProductsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listProductsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsWithDetailsRow
	for rows.Next() {
		var i ListProductsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductNameID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CheckID,
			&i.CategoryName,
			&i.TotalPurchases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
