// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (product_id, check_id, category_id, price_per_unit, amount_or_weight) 
VALUES ($1, $2, $3, $4, $5) 
ON CONFLICT (product_id, check_id) DO UPDATE 
SET amount_or_weight = products.amount_or_weight + EXCLUDED.amount_or_weight,
    price_per_unit = EXCLUDED.price_per_unit
RETURNING id, product_id, check_id, category_id, price_per_unit, amount_or_weight
`

type CreateProductParams struct {
	ProductID      int32
	CheckID        int32
	CategoryID     int32
	PricePerUnit   float64
	AmountOrWeight float64
}

// on conflict для молочки, идентичные товары идут разными позициями из-за специальных чеков
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductID,
		arg.CheckID,
		arg.CategoryID,
		arg.PricePerUnit,
		arg.AmountOrWeight,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CheckID,
		&i.CategoryID,
		&i.PricePerUnit,
		&i.AmountOrWeight,
	)
	return i, err
}

const getLiveFeed = `-- name: GetLiveFeed :many
SELECT 
    pn.name as product_name,
    b.name as store_name,
    p.price_per_unit as price,
    c.created_at
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
JOIN shops s ON c.shop_id = s.id
JOIN shop_brands b ON s.brand_id = b.id
ORDER BY c.created_at DESC
LIMIT $1::int
`

type GetLiveFeedRow struct {
	ProductName string
	StoreName   string
	Price       float64
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetLiveFeed(ctx context.Context, limitParam int32) ([]GetLiveFeedRow, error) {
	rows, err := q.db.Query(ctx, getLiveFeed, limitParam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveFeedRow
	for rows.Next() {
		var i GetLiveFeedRow
		if err := rows.Scan(
			&i.ProductName,
			&i.StoreName,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, product_id, check_id, category_id, price_per_unit, amount_or_weight FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CheckID,
		&i.CategoryID,
		&i.PricePerUnit,
		&i.AmountOrWeight,
	)
	return i, err
}

const getProductPriceHistory = `-- name: GetProductPriceHistory :many
SELECT 
    c.created_at,
    p.price_per_unit,
    p.amount_or_weight,
    c.check_id
FROM products p
JOIN checks c ON p.check_id = c.id
WHERE p.product_id = $1
ORDER BY c.created_at DESC
`

type GetProductPriceHistoryRow struct {
	CreatedAt      pgtype.Timestamp
	PricePerUnit   float64
	AmountOrWeight float64
	CheckID        string
}

func (q *Queries) GetProductPriceHistory(ctx context.Context, productID int32) ([]GetProductPriceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getProductPriceHistory, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductPriceHistoryRow
	for rows.Next() {
		var i GetProductPriceHistoryRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.CheckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithDetails = `-- name: GetProductWithDetails :one
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name
FROM products p
JOIN product_names pn ON p.product_id = pn.id
WHERE p.id = $1
`

type GetProductWithDetailsRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
}

func (q *Queries) GetProductWithDetails(ctx context.Context, id int32) (GetProductWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProductWithDetails, id)
	var i GetProductWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.PricePerUnit,
		&i.AmountOrWeight,
		&i.ProductName,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    cat.name as category_name,
    c.check_id as check_id,
    c.created_at
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN categories cat ON p.category_id = cat.id
JOIN checks c ON p.check_id = c.id
WHERE cat.id = $1
AND ($2::timestamp IS NULL OR c.created_at >= $2)
AND ($3::timestamp IS NULL OR c.created_at <= $3)
`

type GetProductsByCategoryParams struct {
	ID      int32
	Column2 pgtype.Timestamp
	Column3 pgtype.Timestamp
}

type GetProductsByCategoryRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CategoryName   string
	CheckID        string
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetProductsByCategory(ctx context.Context, arg GetProductsByCategoryParams) ([]GetProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getProductsByCategory, arg.ID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCategoryRow
	for rows.Next() {
		var i GetProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CategoryName,
			&i.CheckID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByCheckCount = `-- name: GetProductsByCheckCount :many
SELECT 
    pn.id,
    pn.name,
    COUNT(DISTINCT p.check_id) as check_count,
    COUNT(p.id) as total_entries
FROM product_names pn
LEFT JOIN products p ON pn.id = p.product_id
GROUP BY pn.id, pn.name
HAVING COUNT(DISTINCT p.check_id) >= $1
ORDER BY check_count DESC
`

type GetProductsByCheckCountRow struct {
	ID           int32
	Name         string
	CheckCount   int64
	TotalEntries int64
}

func (q *Queries) GetProductsByCheckCount(ctx context.Context, checkID int32) ([]GetProductsByCheckCountRow, error) {
	rows, err := q.db.Query(ctx, getProductsByCheckCount, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCheckCountRow
	for rows.Next() {
		var i GetProductsByCheckCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CheckCount,
			&i.TotalEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByCheckID = `-- name: GetProductsByCheckID :many
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    c.check_id as check_id,
    c.created_at
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
WHERE p.check_id = $1
AND ($2::timestamp IS NULL OR c.created_at >= $2)
AND ($3::timestamp IS NULL OR c.created_at <= $3)
`

type GetProductsByCheckIDParams struct {
	CheckID int32
	Column2 pgtype.Timestamp
	Column3 pgtype.Timestamp
}

type GetProductsByCheckIDRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CheckID        string
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetProductsByCheckID(ctx context.Context, arg GetProductsByCheckIDParams) ([]GetProductsByCheckIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByCheckID, arg.CheckID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByCheckIDRow
	for rows.Next() {
		var i GetProductsByCheckIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CheckID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByDateRange = `-- name: GetProductsByDateRange :many
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    c.check_id as check_id,
    c.created_at
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
WHERE ($1::timestamp IS NULL OR c.created_at >= $1)
AND ($2::timestamp IS NULL OR c.created_at <= $2)
ORDER BY c.created_at DESC
`

type GetProductsByDateRangeParams struct {
	Column1 pgtype.Timestamp
	Column2 pgtype.Timestamp
}

type GetProductsByDateRangeRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CheckID        string
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetProductsByDateRange(ctx context.Context, arg GetProductsByDateRangeParams) ([]GetProductsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getProductsByDateRange, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByDateRangeRow
	for rows.Next() {
		var i GetProductsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CheckID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByName = `-- name: GetProductsByName :many
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    c.check_id as check_id,
    c.created_at
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
WHERE pn.name ILIKE '%' || $1 || '%'
ORDER BY c.created_at DESC
`

type GetProductsByNameRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CheckID        string
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetProductsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetProductsByNameRow, error) {
	rows, err := q.db.Query(ctx, getProductsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByNameRow
	for rows.Next() {
		var i GetProductsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CheckID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCheckID = `-- name: ListProductsByCheckID :many
SELECT id, product_id, check_id, category_id, price_per_unit, amount_or_weight FROM products WHERE check_id = $1
`

func (q *Queries) ListProductsByCheckID(ctx context.Context, checkID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCheckID, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CheckID,
			&i.CategoryID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByProductNameID = `-- name: ListProductsByProductNameID :many
SELECT id, product_id, check_id, category_id, price_per_unit, amount_or_weight FROM products WHERE product_id = $1
`

func (q *Queries) ListProductsByProductNameID(ctx context.Context, productID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByProductNameID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CheckID,
			&i.CategoryID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithDetails = `-- name: ListProductsWithDetails :many
SELECT 
    p.id,
    p.price_per_unit,
    p.amount_or_weight,
    pn.name as product_name,
    c.check_id as check_id
FROM products p
JOIN product_names pn ON p.product_id = pn.id
JOIN checks c ON p.check_id = c.id
ORDER BY p.id
`

type ListProductsWithDetailsRow struct {
	ID             int32
	PricePerUnit   float64
	AmountOrWeight float64
	ProductName    string
	CheckID        string
}

func (q *Queries) ListProductsWithDetails(ctx context.Context) ([]ListProductsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listProductsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsWithDetailsRow
	for rows.Next() {
		var i ListProductsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ProductName,
			&i.CheckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
