// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareShopsByTemplateWithBreakdown = `-- name: CompareShopsByTemplateWithBreakdown :many
WITH matching_products AS (
    SELECT pn2.id, req.name as requested_name
    FROM product_names pn2
    CROSS JOIN unnest($1::text[]) req(name)
    WHERE pn2.name = req.name
    UNION
    SELECT pr.identical_product_name_id, req.name
    FROM product_relations pr
    CROSS JOIN unnest($1::text[]) req(name)
    JOIN product_names pn_req ON pn_req.name = req.name
    WHERE pr.product_name_id = pn_req.id
    UNION
    SELECT pr.product_name_id, req.name
    FROM product_relations pr
    CROSS JOIN unnest($1::text[]) req(name)
    JOIN product_names pn_req ON pn_req.name = req.name
    WHERE pr.identical_product_name_id = pn_req.id
),
all_template_products AS (
    SELECT DISTINCT mp.requested_name
    FROM matching_products mp
),
shop_products AS (
    SELECT DISTINCT ON (mp.requested_name, c.shop_id)
        c.shop_id,
        mp.requested_name,
        pn.name as product_name,
        p.price_per_unit,
        p.amount_or_weight,
        (p.price_per_unit * p.amount_or_weight)::float8 as item_total
    FROM checks c
    JOIN products p ON c.id = p.check_id
    JOIN product_names pn ON p.product_id = pn.id
    JOIN matching_products mp ON pn.id = mp.id
    ORDER BY mp.requested_name, c.shop_id, c.created_at DESC
)
SELECT 
    s.id,
    b.name as brand_name,
    s.address,
    atp.requested_name,
    COALESCE(sp.product_name, atp.requested_name) as product_name,
    sp.price_per_unit,
    sp.amount_or_weight,
    sp.item_total
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
CROSS JOIN all_template_products atp
LEFT JOIN shop_products sp ON s.id = sp.shop_id AND atp.requested_name = sp.requested_name
ORDER BY s.id, atp.requested_name
`

type CompareShopsByTemplateWithBreakdownRow struct {
	ID             int32
	BrandName      string
	Address        string
	RequestedName  interface{}
	ProductName    string
	PricePerUnit   pgtype.Float8
	AmountOrWeight pgtype.Float8
	ItemTotal      pgtype.Float8
}

func (q *Queries) CompareShopsByTemplateWithBreakdown(ctx context.Context, dollar_1 []string) ([]CompareShopsByTemplateWithBreakdownRow, error) {
	rows, err := q.db.Query(ctx, compareShopsByTemplateWithBreakdown, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareShopsByTemplateWithBreakdownRow
	for rows.Next() {
		var i CompareShopsByTemplateWithBreakdownRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandName,
			&i.Address,
			&i.RequestedName,
			&i.ProductName,
			&i.PricePerUnit,
			&i.AmountOrWeight,
			&i.ItemTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (brand_id, address) 
VALUES ($1, $2) 
ON CONFLICT (brand_id, address) DO NOTHING 
RETURNING id, brand_id, address, lat, lng
`

type CreateShopParams struct {
	BrandID int32
	Address string
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop, arg.BrandID, arg.Address)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shops WHERE id = $1
`

func (q *Queries) DeleteShop(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteShop, id)
	return err
}

const getShopByAddress = `-- name: GetShopByAddress :one
SELECT id, brand_id, address, lat, lng FROM shops WHERE address = $1
`

func (q *Queries) GetShopByAddress(ctx context.Context, address string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByAddress, address)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
WHERE s.id = $1
`

type GetShopByIDRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
}

func (q *Queries) GetShopByID(ctx context.Context, id int32) (GetShopByIDRow, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i GetShopByIDRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.BrandName,
	)
	return i, err
}

const getShopStats = `-- name: GetShopStats :one
SELECT 
    s.id,
    b.name as brand_name,
    s.address,
    COUNT(DISTINCT c.id) as check_count,
    COUNT(p.id) as product_count,
    AVG(p.price_per_unit) as avg_price
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
LEFT JOIN checks c ON s.id = c.shop_id
LEFT JOIN products p ON c.id = p.check_id
WHERE s.id = $1
GROUP BY s.id, b.name, s.address
`

type GetShopStatsRow struct {
	ID           int32
	BrandName    string
	Address      string
	CheckCount   int64
	ProductCount int64
	AvgPrice     float64
}

func (q *Queries) GetShopStats(ctx context.Context, id int32) (GetShopStatsRow, error) {
	row := q.db.QueryRow(ctx, getShopStats, id)
	var i GetShopStatsRow
	err := row.Scan(
		&i.ID,
		&i.BrandName,
		&i.Address,
		&i.CheckCount,
		&i.ProductCount,
		&i.AvgPrice,
	)
	return i, err
}

const getShopsByBrand = `-- name: GetShopsByBrand :many
SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
WHERE b.name = $1
ORDER BY s.address
`

type GetShopsByBrandRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
}

func (q *Queries) GetShopsByBrand(ctx context.Context, name string) ([]GetShopsByBrandRow, error) {
	rows, err := q.db.Query(ctx, getShopsByBrand, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShopsByBrandRow
	for rows.Next() {
		var i GetShopsByBrandRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShopsNearby = `-- name: GetShopsNearby :many
SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name,
    ( 6371 * acos( cos( radians($1::float8) ) * cos( radians(s.lat) ) * cos( radians(s.lng) - radians($2::float8) ) + sin( radians($1::float8) ) * sin( radians(s.lat) ) ) ) AS distance
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
WHERE s.lat IS NOT NULL AND s.lng IS NOT NULL
    AND ( 6371 * acos( cos( radians($1::float8) ) * cos( radians(s.lat) ) * cos( radians(s.lng) - radians($2::float8) ) + sin( radians($1::float8) ) * sin( radians(s.lat) ) ) ) < $3::float8
ORDER BY distance
LIMIT $4::int
`

type GetShopsNearbyParams struct {
	LatParam    float64
	LngParam    float64
	RadiusParam float64
	LimitParam  int32
}

type GetShopsNearbyRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
	Distance  int32
}

func (q *Queries) GetShopsNearby(ctx context.Context, arg GetShopsNearbyParams) ([]GetShopsNearbyRow, error) {
	rows, err := q.db.Query(ctx, getShopsNearby,
		arg.LatParam,
		arg.LngParam,
		arg.RadiusParam,
		arg.LimitParam,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShopsNearbyRow
	for rows.Next() {
		var i GetShopsNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.BrandName,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShops = `-- name: ListShops :many

SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
ORDER BY b.name
`

type ListShopsRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
}

// database/query/shops.sql
func (q *Queries) ListShops(ctx context.Context) ([]ListShopsRow, error) {
	rows, err := q.db.Query(ctx, listShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopsRow
	for rows.Next() {
		var i ListShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShops = `-- name: SearchShops :many
SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
WHERE b.name ILIKE '%' || $1 || '%' OR s.address ILIKE '%' || $1 || '%'
ORDER BY b.name
`

type SearchShopsRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
}

func (q *Queries) SearchShops(ctx context.Context, dollar_1 pgtype.Text) ([]SearchShopsRow, error) {
	rows, err := q.db.Query(ctx, searchShops, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchShopsRow
	for rows.Next() {
		var i SearchShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShopsWithLocation = `-- name: SearchShopsWithLocation :many
SELECT s.id, s.brand_id, s.address, s.lat, s.lng, b.name as brand_name
FROM shops s
JOIN shop_brands b ON s.brand_id = b.id
WHERE (b.name ILIKE '%' || $1 || '%' OR s.address ILIKE '%' || $1 || '%')
AND s.lat IS NOT NULL AND s.lng IS NOT NULL
ORDER BY b.name
`

type SearchShopsWithLocationRow struct {
	ID        int32
	BrandID   int32
	Address   string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	BrandName string
}

func (q *Queries) SearchShopsWithLocation(ctx context.Context, dollar_1 pgtype.Text) ([]SearchShopsWithLocationRow, error) {
	rows, err := q.db.Query(ctx, searchShopsWithLocation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchShopsWithLocationRow
	for rows.Next() {
		var i SearchShopsWithLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops 
SET address = $2, lat = $3, lng = $4
WHERE id = $1
RETURNING id, brand_id, address, lat, lng
`

type UpdateShopParams struct {
	ID      int32
	Address string
	Lat     pgtype.Float8
	Lng     pgtype.Float8
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Address,
		arg.Lat,
		arg.Lng,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}
