// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop_brands.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO shop_brands (name) 
VALUES ($1) 
ON CONFLICT (name) DO NOTHING 
RETURNING id, name
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (ShopBrand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i ShopBrand
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM shop_brands WHERE id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBrand, id)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name FROM shop_brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id int32) (ShopBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i ShopBrand
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBrandByName = `-- name: GetBrandByName :one
SELECT id, name FROM shop_brands WHERE name = $1
`

func (q *Queries) GetBrandByName(ctx context.Context, name string) (ShopBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByName, name)
	var i ShopBrand
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name FROM shop_brands ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]ShopBrand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopBrand
	for rows.Next() {
		var i ShopBrand
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBrands = `-- name: SearchBrands :many
SELECT id, name FROM shop_brands WHERE name ILIKE '%' || $1 || '%' ORDER BY name
`

func (q *Queries) SearchBrands(ctx context.Context, dollar_1 pgtype.Text) ([]ShopBrand, error) {
	rows, err := q.db.Query(ctx, searchBrands, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopBrand
	for rows.Next() {
		var i ShopBrand
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE shop_brands 
SET name = $2 
WHERE id = $1 
RETURNING id, name
`

type UpdateBrandParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (ShopBrand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.ID, arg.Name)
	var i ShopBrand
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
