// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareShopsByTemplate = `-- name: CompareShopsByTemplate :many
SELECT 
    s.id,
    s.name,
    s.address,
    SUM(p.price_per_unit * p.amount_or_weight) as total_price,
    COUNT(p.id) as product_count
FROM shops s
JOIN checks c ON s.id = c.shop_id
JOIN products p ON c.id = p.check_id
JOIN product_names pn ON p.product_id = pn.id
WHERE pn.name = ANY($1::text[])
GROUP BY s.id, s.name, s.address
ORDER BY total_price ASC
`

type CompareShopsByTemplateRow struct {
	ID           int32
	Name         string
	Address      string
	TotalPrice   int64
	ProductCount int64
}

func (q *Queries) CompareShopsByTemplate(ctx context.Context, dollar_1 []string) ([]CompareShopsByTemplateRow, error) {
	rows, err := q.db.Query(ctx, compareShopsByTemplate, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompareShopsByTemplateRow
	for rows.Next() {
		var i CompareShopsByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TotalPrice,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (name, address, lat, lng) 
VALUES ($1, $2, NULL, NULL) 
ON CONFLICT (name) DO NOTHING 
RETURNING id, name, address, lat, lng
`

type CreateShopParams struct {
	Name    string
	Address string
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop, arg.Name, arg.Address)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shops WHERE id = $1
`

func (q *Queries) DeleteShop(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteShop, id)
	return err
}

const getShopByAddress = `-- name: GetShopByAddress :one
SELECT id, name, address, lat, lng FROM shops WHERE address = $1
`

func (q *Queries) GetShopByAddress(ctx context.Context, address string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByAddress, address)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, name, address, lat, lng FROM shops WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id int32) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getShopByName = `-- name: GetShopByName :one
SELECT id, name, address, lat, lng FROM shops WHERE name = $1
`

func (q *Queries) GetShopByName(ctx context.Context, name string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByName, name)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getShopStats = `-- name: GetShopStats :one
SELECT 
    s.id,
    s.name,
    s.address,
    COUNT(DISTINCT c.id) as check_count,
    COUNT(p.id) as product_count,
    AVG(p.price_per_unit) as avg_price
FROM shops s
LEFT JOIN checks c ON s.id = c.shop_id
LEFT JOIN products p ON c.id = p.check_id
WHERE s.id = $1
GROUP BY s.id, s.name, s.address
`

type GetShopStatsRow struct {
	ID           int32
	Name         string
	Address      string
	CheckCount   int64
	ProductCount int64
	AvgPrice     float64
}

func (q *Queries) GetShopStats(ctx context.Context, id int32) (GetShopStatsRow, error) {
	row := q.db.QueryRow(ctx, getShopStats, id)
	var i GetShopStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CheckCount,
		&i.ProductCount,
		&i.AvgPrice,
	)
	return i, err
}

const getShopsNearby = `-- name: GetShopsNearby :many
SELECT id, name, address, lat, lng,
    ( 6371 * acos( cos( radians($1::float8) ) * cos( radians(lat) ) * cos( radians(lng) - radians($2::float8) ) + sin( radians($1::float8) ) * sin( radians(lat) ) ) ) AS distance
FROM shops
WHERE lat IS NOT NULL AND lng IS NOT NULL
    AND ( 6371 * acos( cos( radians($1::float8) ) * cos( radians(lat) ) * cos( radians(lng) - radians($2::float8) ) + sin( radians($1::float8) ) * sin( radians(lat) ) ) ) < $3::float8
ORDER BY distance
LIMIT $4::int
`

type GetShopsNearbyParams struct {
	LatParam    float64
	LngParam    float64
	RadiusParam float64
	LimitParam  int32
}

type GetShopsNearbyRow struct {
	ID       int32
	Name     string
	Address  string
	Lat      pgtype.Float8
	Lng      pgtype.Float8
	Distance int32
}

func (q *Queries) GetShopsNearby(ctx context.Context, arg GetShopsNearbyParams) ([]GetShopsNearbyRow, error) {
	rows, err := q.db.Query(ctx, getShopsNearby,
		arg.LatParam,
		arg.LngParam,
		arg.RadiusParam,
		arg.LimitParam,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShopsNearbyRow
	for rows.Next() {
		var i GetShopsNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShops = `-- name: ListShops :many

SELECT id, name, address, lat, lng FROM shops ORDER BY name
`

// database/query/shops.sql
func (q *Queries) ListShops(ctx context.Context) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShops = `-- name: SearchShops :many
SELECT id, name, address, lat, lng
FROM shops
WHERE name ILIKE '%' || $1 || '%' OR address ILIKE '%' || $1 || '%'
ORDER BY name
`

func (q *Queries) SearchShops(ctx context.Context, dollar_1 pgtype.Text) ([]Shop, error) {
	rows, err := q.db.Query(ctx, searchShops, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShopsWithLocation = `-- name: SearchShopsWithLocation :many
SELECT id, name, address, lat, lng FROM shops
WHERE (name ILIKE '%' || $1::text || '%' OR address ILIKE '%' || $1::text || '%')
AND lat IS NOT NULL AND lng IS NOT NULL
ORDER BY name
`

func (q *Queries) SearchShopsWithLocation(ctx context.Context, dollar_1 string) ([]Shop, error) {
	rows, err := q.db.Query(ctx, searchShopsWithLocation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops 
SET name = $2, address = $3
WHERE id = $1
RETURNING id, name, address
`

type UpdateShopParams struct {
	ID      int32
	Name    string
	Address string
}

type UpdateShopRow struct {
	ID      int32
	Name    string
	Address string
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (UpdateShopRow, error) {
	row := q.db.QueryRow(ctx, updateShop, arg.ID, arg.Name, arg.Address)
	var i UpdateShopRow
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}
