// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"
)

const getCategoryStats = `-- name: GetCategoryStats :one
SELECT 
    cat.id,
    cat.name,
    COUNT(p.id) as product_count,
    COUNT(DISTINCT p.check_id) as check_count,
    AVG(p.price_per_unit) as avg_price
FROM categories cat
LEFT JOIN products p ON cat.id = p.category_id
WHERE cat.id = $1
GROUP BY cat.id, cat.name
`

type GetCategoryStatsRow struct {
	ID           int32
	Name         string
	ProductCount int64
	CheckCount   int64
	AvgPrice     float64
}

func (q *Queries) GetCategoryStats(ctx context.Context, id int32) (GetCategoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getCategoryStats, id)
	var i GetCategoryStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductCount,
		&i.CheckCount,
		&i.AvgPrice,
	)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT 
    (SELECT COUNT(*) FROM checks) as total_checks,
    (SELECT COUNT(*) FROM product_names) as total_unique_products,
    (SELECT COUNT(*) FROM products) as total_product_entries
`

type GetStatsRow struct {
	TotalChecks         int64
	TotalUniqueProducts int64
	TotalProductEntries int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(&i.TotalChecks, &i.TotalUniqueProducts, &i.TotalProductEntries)
	return i, err
}
