// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductToTemplate = `-- name: AddProductToTemplate :exec
INSERT INTO template_products (template_id, product_name_id) 
VALUES ($1::int, $2::int) 
ON CONFLICT (template_id, product_name_id) DO NOTHING
`

type AddProductToTemplateParams struct {
	TemplateID    int32
	ProductNameID int32
}

func (q *Queries) AddProductToTemplate(ctx context.Context, arg AddProductToTemplateParams) error {
	_, err := q.db.Exec(ctx, addProductToTemplate, arg.TemplateID, arg.ProductNameID)
	return err
}

const clearTemplateProducts = `-- name: ClearTemplateProducts :exec
DELETE FROM template_products WHERE template_id = $1::int
`

func (q *Queries) ClearTemplateProducts(ctx context.Context, templateID int32) error {
	_, err := q.db.Exec(ctx, clearTemplateProducts, templateID)
	return err
}

const copyTemplate = `-- name: CopyTemplate :one
WITH new_template AS (
    INSERT INTO templates (name, user_id, is_default) 
    VALUES ($2::text, $3::int, FALSE) 
    RETURNING id, name, user_id, is_default, created_at
)
INSERT INTO template_products (template_id, product_name_id)
SELECT new_template.id, tp.product_name_id
FROM new_template
CROSS JOIN template_products tp
WHERE tp.template_id = $1::int
RETURNING (SELECT id, name, user_id, is_default, created_at FROM new_template)
`

type CopyTemplateParams struct {
	TemplateID int32
	Name       string
	UserID     int32
}

func (q *Queries) CopyTemplate(ctx context.Context, arg CopyTemplateParams) (int32, error) {
	row := q.db.QueryRow(ctx, copyTemplate, arg.TemplateID, arg.Name, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, user_id, is_default) 
VALUES ($1::text, $2::int, $3::bool) 
RETURNING id, name, user_id, is_default, created_at
`

type CreateTemplateParams struct {
	Name      string
	UserID    int32
	IsDefault bool
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Name, arg.UserID, arg.IsDefault)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1::int
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, user_id, is_default, created_at FROM templates WHERE id = $1::int
`

func (q *Queries) GetTemplateByID(ctx context.Context, id int32) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateWithProducts = `-- name: GetTemplateWithProducts :many
SELECT 
    t.id,
    t.name,
    t.user_id,
    t.is_default,
    t.created_at,
    pn.id as product_id,
    pn.name as product_name
FROM templates t
LEFT JOIN template_products tp ON t.id = tp.template_id
LEFT JOIN product_names pn ON tp.product_name_id = pn.id
WHERE t.id = $1::int
ORDER BY pn.name
`

type GetTemplateWithProductsRow struct {
	ID          int32
	Name        string
	UserID      pgtype.Int4
	IsDefault   pgtype.Bool
	CreatedAt   pgtype.Timestamp
	ProductID   pgtype.Int4
	ProductName pgtype.Text
}

func (q *Queries) GetTemplateWithProducts(ctx context.Context, id int32) ([]GetTemplateWithProductsRow, error) {
	rows, err := q.db.Query(ctx, getTemplateWithProducts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTemplateWithProductsRow
	for rows.Next() {
		var i GetTemplateWithProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsDefault,
			&i.CreatedAt,
			&i.ProductID,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultTemplates = `-- name: ListDefaultTemplates :many
SELECT id, name, user_id, is_default, created_at FROM templates WHERE is_default = TRUE ORDER BY name
`

func (q *Queries) ListDefaultTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listDefaultTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateProducts = `-- name: ListTemplateProducts :many
SELECT pn.id, pn.name
FROM template_products tp
JOIN product_names pn ON tp.product_name_id = pn.id
WHERE tp.template_id = $1::int
ORDER BY pn.name
`

func (q *Queries) ListTemplateProducts(ctx context.Context, templateID int32) ([]ProductName, error) {
	rows, err := q.db.Query(ctx, listTemplateProducts, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductName
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many

SELECT id, name, user_id, is_default, created_at FROM templates ORDER BY name
`

// database/query/templates.sql
func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTemplates = `-- name: ListUserTemplates :many
SELECT id, name, user_id, is_default, created_at FROM templates WHERE user_id = $1::int ORDER BY name
`

func (q *Queries) ListUserTemplates(ctx context.Context, userID int32) ([]Template, error) {
	rows, err := q.db.Query(ctx, listUserTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductFromTemplate = `-- name: RemoveProductFromTemplate :exec
DELETE FROM template_products 
WHERE template_id = $1::int AND product_name_id = $2::int
`

type RemoveProductFromTemplateParams struct {
	TemplateID    int32
	ProductNameID int32
}

func (q *Queries) RemoveProductFromTemplate(ctx context.Context, arg RemoveProductFromTemplateParams) error {
	_, err := q.db.Exec(ctx, removeProductFromTemplate, arg.TemplateID, arg.ProductNameID)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates 
SET name = $1::text, user_id = $2::int, is_default = $3::bool
WHERE id = $4::int
RETURNING id, name, user_id, is_default, created_at
`

type UpdateTemplateParams struct {
	Name      string
	UserID    int32
	IsDefault bool
	ID        int32
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.UserID,
		arg.IsDefault,
		arg.ID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
