// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, name) 
VALUES ($1::text, $2::text, $3::text) 
RETURNING id, email, password_hash, name, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

// database/query/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT 
    COUNT(DISTINCT c.id) as total_checks,
    COUNT(DISTINCT p.id) as total_products,
    COUNT(DISTINCT pn.id) as total_unique_products
FROM users u
LEFT JOIN checks c ON u.id = c.user_id
LEFT JOIN products p ON c.id = p.check_id
LEFT JOIN product_names pn ON p.product_id = pn.id
WHERE u.id = $1
`

type GetUserStatsRow struct {
	TotalChecks         int64
	TotalProducts       int64
	TotalUniqueProducts int64
}

func (q *Queries) GetUserStats(ctx context.Context, id int32) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, id)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalChecks, &i.TotalProducts, &i.TotalUniqueProducts)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users 
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET name = $1::text, email = $2::text
WHERE id = $3::int
RETURNING id, email, password_hash, name, created_at
`

type UpdateUserParams struct {
	Name  string
	Email string
	ID    int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
