-- Create "checks" table
CREATE TABLE "public"."checks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "check_id" character varying NOT NULL,
  "file_name" character varying NOT NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "checks_check_id_key" to table: "checks"
CREATE UNIQUE INDEX "checks_check_id_key" ON "public"."checks" ("check_id");
-- Create "product_names" table
CREATE TABLE "public"."product_names" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "product_names_name_key" to table: "product_names"
CREATE UNIQUE INDEX "product_names_name_key" ON "public"."product_names" ("name");
-- Create "products" table
CREATE TABLE "public"."products" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "price" double precision NOT NULL,
  "quantity" double precision NOT NULL,
  "check_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "products_checks_products" FOREIGN KEY ("check_id") REFERENCES "public"."checks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "products_product_names_products" FOREIGN KEY ("product_id") REFERENCES "public"."product_names" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
