// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_names.sql

package sqlc

import (
	"context"
)

const createProductName = `-- name: CreateProductName :one
INSERT INTO product_names (name) 
VALUES ($1) 
ON CONFLICT (name) DO NOTHING 
RETURNING id, name
`

func (q *Queries) CreateProductName(ctx context.Context, name string) (ProductName, error) {
	row := q.db.QueryRow(ctx, createProductName, name)
	var i ProductName
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateProductName = `-- name: GetOrCreateProductName :one
WITH inserted AS (
    INSERT INTO product_names (name) 
    VALUES ($1) 
    ON CONFLICT (name) DO NOTHING 
    RETURNING id, name
)
SELECT id, name FROM inserted
UNION ALL
SELECT id, name FROM product_names WHERE name = $1
LIMIT 1
`

type GetOrCreateProductNameRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetOrCreateProductName(ctx context.Context, name string) (GetOrCreateProductNameRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateProductName, name)
	var i GetOrCreateProductNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProductNameByID = `-- name: GetProductNameByID :one
SELECT id, name FROM product_names WHERE id = $1
`

func (q *Queries) GetProductNameByID(ctx context.Context, id int32) (ProductName, error) {
	row := q.db.QueryRow(ctx, getProductNameByID, id)
	var i ProductName
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProductNameByName = `-- name: GetProductNameByName :one
SELECT id, name FROM product_names WHERE name = $1
`

func (q *Queries) GetProductNameByName(ctx context.Context, name string) (ProductName, error) {
	row := q.db.QueryRow(ctx, getProductNameByName, name)
	var i ProductName
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listProductNames = `-- name: ListProductNames :many
SELECT id, name FROM product_names ORDER BY name
`

func (q *Queries) ListProductNames(ctx context.Context) ([]ProductName, error) {
	rows, err := q.db.Query(ctx, listProductNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductName
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductNamesWithCount = `-- name: ListProductNamesWithCount :many
SELECT 
    pn.id,
    pn.name,
    COUNT(p.product_id) as usage_count
FROM product_names pn
LEFT JOIN products p ON pn.id = p.product_id
GROUP BY pn.id, pn.name
ORDER BY usage_count DESC, pn.name
`

type ListProductNamesWithCountRow struct {
	ID         int32
	Name       string
	UsageCount int64
}

func (q *Queries) ListProductNamesWithCount(ctx context.Context) ([]ListProductNamesWithCountRow, error) {
	rows, err := q.db.Query(ctx, listProductNamesWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductNamesWithCountRow
	for rows.Next() {
		var i ListProductNamesWithCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
